### ISSUE TITLE
Not running on Heroku

### ISSUE THREAD

**Issue by MawiraIke** [MawiraIke/django-implementation#1]
The project is not running on Heroku. What could be wrong?
Heroku link: https://django-tut.herokuapp.com/

Here are the log files 

```
2019-10-21T07:59:07.068954+00:00 app[api]: Release v2 created by user mawiraike@gmail.com
2019-10-21T07:59:06.893855+00:00 app[api]: Initial release by user mawiraike@gmail.com
2019-10-21T07:59:07.068954+00:00 app[api]: Enable Logplex by user mawiraike@gmail.com
2019-10-21T07:59:06.893855+00:00 app[api]: Release v1 created by user mawiraike@gmail.com
2019-10-21T08:04:46+00:00 app[api]: Build started by user mawiraike@gmail.com
2019-10-21T08:05:39.379994+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/" host=django-tut.herokuapp.com request_id=3aea935b-c2bd-432c-82a2-ff48e8c3eab6 fwd="154.157.114.244" dyno= connect= service= status=502 bytes= protocol=https
2019-10-21T08:05:39.993264+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/favicon.ico" host=django-tut.herokuapp.com request_id=d2b13aec-c932-45d8-97cd-29ee76d62cfa fwd="154.157.114.244" dyno= connect= service= status=502 bytes= protocol=https
2019-10-21T08:05:40.082199+00:00 app[api]: Attach DATABASE (@ref:postgresql-cubed-76433) by user mawiraike@gmail.com
2019-10-21T08:05:40.099753+00:00 app[api]: @ref:postgresql-cubed-76433 completed provisioning, setting DATABASE_URL. by user mawiraike@gmail.com
2019-10-21T08:05:40.099753+00:00 app[api]: Release v4 created by user mawiraike@gmail.com
2019-10-21T08:08:50.357036+00:00 app[api]: Deploy ab803b09 by user mawiraike@gmail.com
2019-10-21T08:08:50.357036+00:00 app[api]: Release v7 created by user mawiraike@gmail.com
2019-10-21T08:08:51.557751+00:00 heroku[web.1]: State changed from crashed to starting
2019-10-21T08:08:56.055966+00:00 heroku[web.1]: Starting process with command `gunicorn blog_project.wsgi --log-file -`
2019-10-21T08:08:58.026266+00:00 heroku[web.1]: Process exited with status 3
2019-10-21T08:08:58.065374+00:00 heroku[web.1]: State changed from starting to crashed
2019-10-21T08:08:57.940045+00:00 app[web.1]: [2019-10-21 08:08:57 +0000] [4] [INFO] Starting gunicorn 19.9.0
2019-10-21T08:08:57.940606+00:00 app[web.1]: [2019-10-21 08:08:57 +0000] [4] [INFO] Listening at: http://0.0.0.0:27921 (4)
2019-10-21T08:08:57.940723+00:00 app[web.1]: [2019-10-21 08:08:57 +0000] [4] [INFO] Using worker: sync
2019-10-21T08:08:57.944616+00:00 app[web.1]: [2019-10-21 08:08:57 +0000] [10] [INFO] Booting worker with pid: 10
2019-10-21T08:08:57.949549+00:00 app[web.1]: [2019-10-21 08:08:57 +0000] [10] [ERROR] Exception in worker process
2019-10-21T08:08:57.949551+00:00 app[web.1]: Traceback (most recent call last):
2019-10-21T08:08:57.949552+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-10-21T08:08:57.949554+00:00 app[web.1]:     worker.init_process()
2019-10-21T08:08:57.949555+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-10-21T08:08:57.949556+00:00 app[web.1]:     self.load_wsgi()
2019-10-21T08:08:57.949556+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-10-21T08:08:57.949557+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2019-10-21T08:08:57.949559+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-10-21T08:08:57.94956+00:00 app[web.1]:     self.callable = self.load()
2019-10-21T08:08:57.949561+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-10-21T08:08:57.949562+00:00 app[web.1]:     return self.load_wsgiapp()
2019-10-21T08:08:57.949563+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-10-21T08:08:57.949564+00:00 app[web.1]:     return util.import_app(self.app_uri)
2019-10-21T08:08:57.949564+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
2019-10-21T08:08:57.949565+00:00 app[web.1]:     __import__(module)
2019-10-21T08:08:57.94957+00:00 app[web.1]: ModuleNotFoundError: No module named 'blog_project'
2019-10-21T08:08:57.949675+00:00 app[web.1]: [2019-10-21 08:08:57 +0000] [10] [INFO] Worker exiting (pid: 10)
2019-10-21T08:08:57.976164+00:00 app[web.1]: [2019-10-21 08:08:57 +0000] [4] [INFO] Shutting down: Master
2019-10-21T08:08:57.976366+00:00 app[web.1]: [2019-10-21 08:08:57 +0000] [4] [INFO] Reason: Worker failed to boot.
2019-10-21T08:09:00+00:00 app[api]: Build succeeded
2019-10-21T08:12:32+00:00 app[api]: Build started by user mawiraike@gmail.com
2019-10-21T08:12:55.03924+00:00 app[api]: Release v8 created by user mawiraike@gmail.com
2019-10-21T08:12:56.733699+00:00 heroku[web.1]: State changed from crashed to starting
2019-10-21T08:12:55.03924+00:00 app[api]: Deploy 1e5927af by user mawiraike@gmail.com
2019-10-21T08:13:00.903661+00:00 heroku[web.1]: Starting process with command `gunicorn blog_project.wsgi --log-file -`
2019-10-21T08:13:02.317084+00:00 heroku[web.1]: Process exited with status 3
2019-10-21T08:13:02.349924+00:00 heroku[web.1]: State changed from starting to crashed
2019-10-21T08:13:02.233884+00:00 app[web.1]: [2019-10-21 08:13:02 +0000] [4] [INFO] Starting gunicorn 19.9.0
2019-10-21T08:13:02.234356+00:00 app[web.1]: [2019-10-21 08:13:02 +0000] [4] [INFO] Listening at: http://0.0.0.0:47721 (4)
2019-10-21T08:13:02.234457+00:00 app[web.1]: [2019-10-21 08:13:02 +0000] [4] [INFO] Using worker: sync
2019-10-21T08:13:02.237928+00:00 app[web.1]: [2019-10-21 08:13:02 +0000] [10] [INFO] Booting worker with pid: 10
2019-10-21T08:13:02.242457+00:00 app[web.1]: [2019-10-21 08:13:02 +0000] [10] [ERROR] Exception in worker process
2019-10-21T08:13:02.24246+00:00 app[web.1]: Traceback (most recent call last):
2019-10-21T08:13:02.242462+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-10-21T08:13:02.242463+00:00 app[web.1]:     worker.init_process()
2019-10-21T08:13:02.242465+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-10-21T08:13:02.242466+00:00 app[web.1]:     self.load_wsgi()
2019-10-21T08:13:02.242467+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-10-21T08:13:02.242469+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2019-10-21T08:13:02.24247+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-10-21T08:13:02.242471+00:00 app[web.1]:     self.callable = self.load()
2019-10-21T08:13:02.242473+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-10-21T08:13:02.242474+00:00 app[web.1]:     return self.load_wsgiapp()
2019-10-21T08:13:02.242475+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-10-21T08:13:02.242477+00:00 app[web.1]:     return util.import_app(self.app_uri)
2019-10-21T08:13:02.242478+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
2019-10-21T08:13:02.242479+00:00 app[web.1]:     __import__(module)
2019-10-21T08:13:02.242481+00:00 app[web.1]: ModuleNotFoundError: No module named 'blog_project'
2019-10-21T08:13:02.242601+00:00 app[web.1]: [2019-10-21 08:13:02 +0000] [10] [INFO] Worker exiting (pid: 10)
2019-10-21T08:13:02.266179+00:00 app[web.1]: [2019-10-21 08:13:02 +0000] [4] [INFO] Shutting down: Master
2019-10-21T08:13:02.266257+00:00 app[web.1]: [2019-10-21 08:13:02 +0000] [4] [INFO] Reason: Worker failed to boot.
2019-10-21T08:13:05+00:00 app[api]: Build succeeded
2019-10-21T08:15:17+00:00 app[api]: Build started by user mawiraike@gmail.com
2019-10-21T08:15:42.523181+00:00 app[api]: Deploy 848235ed by user mawiraike@gmail.com
2019-10-21T08:15:42.523181+00:00 app[api]: Release v9 created by user mawiraike@gmail.com
2019-10-21T08:15:43.942753+00:00 heroku[web.1]: State changed from crashed to starting
2019-10-21T08:15:49.169877+00:00 heroku[web.1]: Starting process with command `gunicorn blog_project.wsgi --log-file -`
2019-10-21T08:15:51.351043+00:00 heroku[web.1]: Process exited with status 3
2019-10-21T08:15:51.395591+00:00 heroku[web.1]: State changed from starting to crashed
2019-10-21T08:15:51.128846+00:00 app[web.1]: [2019-10-21 08:15:51 +0000] [4] [INFO] Starting gunicorn 19.9.0
2019-10-21T08:15:51.129484+00:00 app[web.1]: [2019-10-21 08:15:51 +0000] [4] [INFO] Listening at: http://0.0.0.0:10661 (4)
2019-10-21T08:15:51.129618+00:00 app[web.1]: [2019-10-21 08:15:51 +0000] [4] [INFO] Using worker: sync
2019-10-21T08:15:51.134532+00:00 app[web.1]: [2019-10-21 08:15:51 +0000] [10] [INFO] Booting worker with pid: 10
2019-10-21T08:15:51.14867+00:00 app[web.1]: [2019-10-21 08:15:51 +0000] [10] [ERROR] Exception in worker process
2019-10-21T08:15:51.148672+00:00 app[web.1]: Traceback (most recent call last):
2019-10-21T08:15:51.148673+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-10-21T08:15:51.148675+00:00 app[web.1]:     worker.init_process()
2019-10-21T08:15:51.148691+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-10-21T08:15:51.148692+00:00 app[web.1]:     self.load_wsgi()
2019-10-21T08:15:51.148694+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-10-21T08:15:51.148695+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2019-10-21T08:15:51.148696+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-10-21T08:15:51.148697+00:00 app[web.1]:     self.callable = self.load()
2019-10-21T08:15:51.148698+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-10-21T08:15:51.148701+00:00 app[web.1]:     return self.load_wsgiapp()
2019-10-21T08:15:51.148701+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-10-21T08:15:51.148703+00:00 app[web.1]:     return util.import_app(self.app_uri)
2019-10-21T08:15:51.148704+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
2019-10-21T08:15:51.148705+00:00 app[web.1]:     __import__(module)
2019-10-21T08:15:51.148711+00:00 app[web.1]: ModuleNotFoundError: No module named 'blog_project'
2019-10-21T08:15:51.148788+00:00 app[web.1]: [2019-10-21 08:15:51 +0000] [10] [INFO] Worker exiting (pid: 10)
2019-10-21T08:15:51.181568+00:00 app[web.1]: [2019-10-21 08:15:51 +0000] [11] [INFO] Booting worker with pid: 11
2019-10-21T08:15:51.188488+00:00 app[web.1]: [2019-10-21 08:15:51 +0000] [11] [ERROR] Exception in worker process
2019-10-21T08:15:51.188491+00:00 app[web.1]: Traceback (most recent call last):
2019-10-21T08:15:51.188493+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-10-21T08:15:51.188494+00:00 app[web.1]:     worker.init_process()
2019-10-21T08:15:51.188496+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-10-21T08:15:51.188497+00:00 app[web.1]:     self.load_wsgi()
2019-10-21T08:15:51.188498+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-10-21T08:15:51.188499+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2019-10-21T08:15:51.188501+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-10-21T08:15:51.188502+00:00 app[web.1]:     self.callable = self.load()
2019-10-21T08:15:51.188504+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-10-21T08:15:51.188505+00:00 app[web.1]:     return self.load_wsgiapp()
2019-10-21T08:15:51.188506+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-10-21T08:15:51.188508+00:00 app[web.1]:     return util.import_app(self.app_uri)
2019-10-21T08:15:51.188509+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
2019-10-21T08:15:51.18851+00:00 app[web.1]:     __import__(module)
2019-10-21T08:15:51.188549+00:00 app[web.1]: ModuleNotFoundError: No module named 'blog_project'
2019-10-21T08:15:51.188821+00:00 app[web.1]: [2019-10-21 08:15:51 +0000] [11] [INFO] Worker exiting (pid: 11)
2019-10-21T08:15:51.290748+00:00 app[web.1]: [2019-10-21 08:15:51 +0000] [4] [INFO] Shutting down: Master
2019-10-21T08:15:51.290836+00:00 app[web.1]: [2019-10-21 08:15:51 +0000] [4] [INFO] Reason: Worker failed to boot.
2019-10-21T08:15:52+00:00 app[api]: Build succeeded
2019-10-21T08:20:52.87352+00:00 heroku[web.1]: State changed from crashed to starting
2019-10-21T08:20:57.72312+00:00 heroku[web.1]: Starting process with command `gunicorn blog_project.wsgi --log-file -`
2019-10-21T08:20:59.91932+00:00 heroku[web.1]: Process exited with status 3
2019-10-21T08:20:59.962387+00:00 heroku[web.1]: State changed from starting to crashed
2019-10-21T08:20:59.703884+00:00 app[web.1]: [2019-10-21 08:20:59 +0000] [4] [INFO] Starting gunicorn 19.9.0
2019-10-21T08:20:59.704441+00:00 app[web.1]: [2019-10-21 08:20:59 +0000] [4] [INFO] Listening at: http://0.0.0.0:57894 (4)
2019-10-21T08:20:59.704531+00:00 app[web.1]: [2019-10-21 08:20:59 +0000] [4] [INFO] Using worker: sync
2019-10-21T08:20:59.708825+00:00 app[web.1]: [2019-10-21 08:20:59 +0000] [10] [INFO] Booting worker with pid: 10
2019-10-21T08:20:59.714817+00:00 app[web.1]: [2019-10-21 08:20:59 +0000] [10] [ERROR] Exception in worker process
2019-10-21T08:20:59.71482+00:00 app[web.1]: Traceback (most recent call last):
2019-10-21T08:20:59.714831+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-10-21T08:20:59.714833+00:00 app[web.1]:     worker.init_process()
2019-10-21T08:20:59.714835+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-10-21T08:20:59.714836+00:00 app[web.1]:     self.load_wsgi()
2019-10-21T08:20:59.714838+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-10-21T08:20:59.714839+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2019-10-21T08:20:59.71485+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-10-21T08:20:59.714852+00:00 app[web.1]:     self.callable = self.load()
2019-10-21T08:20:59.714853+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-10-21T08:20:59.714854+00:00 app[web.1]:     return self.load_wsgiapp()
2019-10-21T08:20:59.714856+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-10-21T08:20:59.714857+00:00 app[web.1]:     return util.import_app(self.app_uri)
2019-10-21T08:20:59.714858+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
2019-10-21T08:20:59.71486+00:00 app[web.1]:     __import__(module)
2019-10-21T08:20:59.714866+00:00 app[web.1]: ModuleNotFoundError: No module named 'blog_project'
2019-10-21T08:20:59.714969+00:00 app[web.1]: [2019-10-21 08:20:59 +0000] [10] [INFO] Worker exiting (pid: 10)
2019-10-21T08:20:59.725553+00:00 app[web.1]: [2019-10-21 08:20:59 +0000] [11] [INFO] Booting worker with pid: 11
2019-10-21T08:20:59.730557+00:00 app[web.1]: [2019-10-21 08:20:59 +0000] [11] [ERROR] Exception in worker process
2019-10-21T08:20:59.73056+00:00 app[web.1]: Traceback (most recent call last):
2019-10-21T08:20:59.730562+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-10-21T08:20:59.730563+00:00 app[web.1]:     worker.init_process()
2019-10-21T08:20:59.730564+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
2019-10-21T08:20:59.730566+00:00 app[web.1]:     self.load_wsgi()
2019-10-21T08:20:59.730567+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2019-10-21T08:20:59.730568+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2019-10-21T08:20:59.73057+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-10-21T08:20:59.730571+00:00 app[web.1]:     self.callable = self.load()
2019-10-21T08:20:59.730573+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2019-10-21T08:20:59.730574+00:00 app[web.1]:     return self.load_wsgiapp()
2019-10-21T08:20:59.730575+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2019-10-21T08:20:59.730577+00:00 app[web.1]:     return util.import_app(self.app_uri)
2019-10-21T08:20:59.730578+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
2019-10-21T08:20:59.730579+00:00 app[web.1]:     __import__(module)
2019-10-21T08:20:59.730584+00:00 app[web.1]: ModuleNotFoundError: No module named 'blog_project'
2019-10-21T08:20:59.730675+00:00 app[web.1]: [2019-10-21 08:20:59 +0000] [11] [INFO] Worker exiting (pid: 11)
2019-10-21T08:20:59.846735+00:00 app[web.1]: [2019-10-21 08:20:59 +0000] [4] [INFO] Shutting down: Master
2019-10-21T08:20:59.846875+00:00 app[web.1]: [2019-10-21 08:20:59 +0000] [4] [INFO] Reason: Worker failed to boot.
2019-10-21T08:21:27.768129+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=django-tut.herokuapp.com request_id=5e233013-e6ff-40bc-a16f-1e6a304da6c4 fwd="154.157.114.244" dyno= connect= service= status=503 bytes= protocol=https
2019-10-21T08:21:28.491292+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=django-tut.herokuapp.com request_id=a79a9edc-173e-408f-9db5-626880d99de5 fwd="154.157.114.244" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by MawiraIke** [comment]
Seems like the exact issue is, 

```python
no module found named blog-project
```

**Comment by brendangaturu** [comment]
Good evening Ike,  we rosolved the issue a while back. Thank you for
trusting in our solutions. Have a merry festive season.
